## Day 21

In [34]:
def getRules(lines):
    rules = {}
    for l in lines:
        k = l.split(" => ")
        rules[k[0]] = k[1]
    return rules

In [80]:
import numpy as np

def S2M(s):
    '''string to matrix'''
    k = s.split("/")
    m = np.zeros((len(k[0]),len(k)),dtype=int)
    y = 0
    for c in k:
        x = 0
        for r in c:
            if r=="#":
                m[y,x] = 1
            x +=1
        y+=1
    return m

def M2S(m):
    '''matrix to string'''
    s = ""
    for y in range(len(m)):
        for x in range(len(m[0])):
            if m[y,x]==1:
                s += "#"
            else:
                s += "."
        s += "/"
    return s[:-1]

def splitM(m):
    if len(m)%2==0:
        split = []
        for j in range(len(m)//2):
            for i in range(len(m[0])//2):
                split.append( m[2*j:2*j+2,2*i:2*i+2] )
        return split
    elif len(m)%3==0:
        split = []
        for j in range(len(m)//3):
            for i in range(len(m[0])//3):
                split.append( m[3*j:3*j+3,3*i:3*i+3] )
        return split

In [131]:
from math import sqrt 

def evolveTiles(rules,n):
    s = ".#./..#/###"
    for e in range(n):
        m = S2M(s)
        splitm = splitM(m)
        lnew = int(sqrt(len(splitm)))*(len(splitm[0])+1)
        mnew = np.zeros((lnew,lnew),dtype=int)
        j = 0
        i = 0
        for mp in splitm:

            foundKey = False
            for _ in range(4):
                mp = np.rot90(mp)
                if M2S(mp) in rules.keys():
                    foundKey = True
                    break
            if not foundKey:
                mp = np.fliplr(mp)
                for _ in range(4):
                    mp = np.rot90(mp)
                    if M2S(mp) in rules.keys():
                        foundKey = True
                        break

            tp = S2M(rules[M2S(mp)])

            # stitch new tiles together
            mnew[j:j+len(tp),i:i+len(tp[0])] = tp
            i = (i+len(tp))%(len(mnew[0]))
            if i==0:
                j+=len(tp)
        s = M2S(mnew)
        print("Evolution {}: size = {}".format(e+1,len(mnew)))
    return s

In [132]:
lines = [
    '../.# => ##./#../...',
    '.#./..#/### => #..#/..../..../#..#'
]

rules =  getRules(lines)

s = evolveTiles(rules,2)
m = S2M(s)
print(m)
print(sum(sum(m)))

Evolution 1: size = 4
Evolution 2: size = 6
[[1 1 0 1 1 0]
 [1 0 0 1 0 0]
 [0 0 0 0 0 0]
 [1 1 0 1 1 0]
 [1 0 0 1 0 0]
 [0 0 0 0 0 0]]
12


In [133]:
with open("data/input21.txt") as f:
    lines = [l.strip("\n") for l in f.readlines()]

rules = getRules(lines)
s = evolveTiles(rules,5)
m = S2M(s)
print(m)
print(sum(sum(m)))

Evolution 1: size = 4
Evolution 2: size = 6
Evolution 3: size = 9
Evolution 4: size = 12
Evolution 5: size = 18
[[1 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1]
 [0 0 1 1 0 1 0 0 1 0 0 1 0 0 1 1 0 1]
 [1 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 1]
 [1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1]
 [0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1]
 [0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1]
 [0 0 1 1 0 1 0 0 1 0 0 1 0 0 1 1 0 1]
 [1 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 1]
 [1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1]
 [0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1]
 [0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1]
 [0 0 1 1 0 1 0 0 1 0 0 1 0 0 1 0 0 1]
 [1 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0]
 [1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1]
 [0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1]
 [0 0 0 1 0 1 0 0 1 0 1 1 1 0 1 1 0 1]]
164


In [134]:
s = evolveTiles(rules,18)
m = S2M(s)
print(sum(sum(m)))

Evolution 1: size = 4
Evolution 2: size = 6
Evolution 3: size = 9
Evolution 4: size = 12
Evolution 5: size = 18
Evolution 6: size = 27
Evolution 7: size = 36
Evolution 8: size = 54
Evolution 9: size = 81
Evolution 10: size = 108
Evolution 11: size = 162
Evolution 12: size = 243
Evolution 13: size = 324
Evolution 14: size = 486
Evolution 15: size = 729
Evolution 16: size = 972
Evolution 17: size = 1458
Evolution 18: size = 2187
2355110
